### ISSUE TITLE
Mailthon on PyPi

### ISSUE THREAD

**Issue by MrLeeh** [eugene-eeo/mailthon#1]
Would be great to have Mailthon available on PyPi

**Comment by eugene-eeo** [comment]
Yes I do realise that it would be nice to have it available on PyPI, but I'm not done with the library yet so I haven't "released" it. What do you think? Should I release it first as a 0.0.0 version or continue working before releasing?

**Comment by oisinmulvihill** [comment]
+1 for PyPi

I'd put it out there now. Its easier for me to install in a virtualenv, then checking out code and setting up the path manually.

**Comment by MrLeeh** [comment]
+1 for PyPi too

As for now it already seems to work. Also you can mark it as alpha or beta version in PyPi.

**Comment by eugene-eeo** [comment]
Will do. Do you know of any ways to make the beta release pull directly from the git repository? Perhaps you guys would want to write a pull request for that.

Also what do you guys think about the header functions? I've added header pairs as functions into the library for convenience purposes.

**Comment by eugene-eeo** [comment]
Ok, so I've registered the project on PyPI. Not too sure about uploading the code now because:

* The API is still in flux and users are likely to experience frequent breakages.
* There may be some obvious bugs within the code that I have yet to squash.
* Testing is not very good yet- I have yet to find a good way to test Mailthon against a fake/real SMTP server. Testing by hand (which is the current approach) is error prone, which mocking the SMTP class is in a way good but may leave out some mistakes.

If you guys have any ideas of how to accomplish something along the lines of

```shell
$ pip install mailthon==dev
```

Or even if that's idiomatic- Flask doesn't seem to support it and the only way to install the latest version is by cloning the repository, which is the more common approach for most other libraries, and is IMHO the better approach especially if the project is still in flux. Also feel free to make some issues or pull requests if you want to help out in the testing department or any other things.
