### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by felipevolpone** [eugene-eeo/mailthon#5]
Do you've some plan to future features of project? I would like to contribute.

**Comment by eugene-eeo** [comment]
Probably more RFC compliance and testing against real or debugging servers. The emphasis of the library is not so much on "throw everything inside" but more about a very polished set of tools, I.e. stability over heaps of features.

That being said feel free to work on these things I have in mind:

 - Internationalised headers
 - Perhaps a SMTP and POP3 adapter so that transports are more swappable, we'll see how that goes

**Comment by eugene-eeo** [comment]
So I've made a head start on internalisation, you can check out the [``internationalised-headers``](https://github.com/eugene-eeo/mailthon/tree/internalionalised-headers) branch and perhaps clone from that. Or submit your own version, I'm okay either way and am open to any suggestions.
